/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniP.view;
import java.net.MalformedURLException;
import java.sql.Date;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import miniP.model.Group;

/**
 *
 * @author mefta
 */
public class group extends javax.swing.JFrame {

    /**
     * Creates new form group
     */
    public group() {
        initComponents();
        table_update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNiveau = new javax.swing.JTextField();
        txtNomGroup = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        date11 = new javax.swing.JLabel();
        heur11 = new javax.swing.JLabel();
        txtHeur = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        txtNb = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        btnConfirmer = new javax.swing.JButton();
        btnGroups = new javax.swing.JButton();
        btnCours = new javax.swing.JButton();
        btnEtrudiants = new javax.swing.JButton();
        btnCreerGroup = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Liste Des Groups");

        jTable1.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom Group", "Nombre d'apprenants", "Niveau", "Nb Séances", "Prochaine Séances", "Heur"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Nom Group");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Niveau");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Prochaine Séance", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 20))); // NOI18N

        date11.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        date11.setForeground(new java.awt.Color(51, 51, 51));
        date11.setText("Date");

        heur11.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        heur11.setForeground(new java.awt.Color(51, 51, 51));
        heur11.setText("Heur");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(date11)
                        .addGap(18, 18, 18)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(heur11)
                        .addGap(18, 18, 18)
                        .addComponent(txtHeur, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date11)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heur11)
                    .addComponent(txtHeur, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombres de Séances", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 20))); // NOI18N

        jButton2.setBackground(new java.awt.Color(0, 153, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(204, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("-");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnConfirmer.setBackground(new java.awt.Color(0, 0, 0));
        btnConfirmer.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnConfirmer.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmer.setText("Confirmer");
        btnConfirmer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNb, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnConfirmer, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNb, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnConfirmer, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btnGroups.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnGroups.setText("Groups");
        btnGroups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroupsActionPerformed(evt);
            }
        });

        btnCours.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnCours.setText("Mes Cours");
        btnCours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoursActionPerformed(evt);
            }
        });

        btnEtrudiants.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnEtrudiants.setText("Etudiants");
        btnEtrudiants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEtrudiantsActionPerformed(evt);
            }
        });

        btnCreerGroup.setBackground(new java.awt.Color(229, 82, 10));
        btnCreerGroup.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnCreerGroup.setForeground(new java.awt.Color(255, 255, 255));
        btnCreerGroup.setText("Créer le group");
        btnCreerGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreerGroupActionPerformed(evt);
            }
        });

        btnModifier.setBackground(new java.awt.Color(0, 51, 153));
        btnModifier.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnModifier.setForeground(new java.awt.Color(255, 255, 255));
        btnModifier.setText("Enregistrer Les Modification");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnSupprimer.setBackground(new java.awt.Color(204, 0, 0));
        btnSupprimer.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnSupprimer.setForeground(new java.awt.Color(255, 255, 255));
        btnSupprimer.setText("Supprimer le group");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNomGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNiveau, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCreerGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 69, Short.MAX_VALUE)
                                .addComponent(btnSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnModifier)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEtrudiants, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCours)
                .addGap(357, 357, 357))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGroups, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCours, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEtrudiants, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNomGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNiveau, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnCreerGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     Connection con1;
        PreparedStatement insert;
        String nomG ;
        static int nombreSeances;
        
        
        private void table_update(){
            int c;
             try {
            Class.forName("com.mysql.cj.jdbc.Driver");   

            String url = "jdbc:mysql://localhost:3306/cour_du_soir?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"; 
            String username = "root";
            String password = "";
            con1 = DriverManager.getConnection(url, username, password);
           
            insert = con1.prepareStatement("select * from groups order by seancesProch");
           ResultSet rs =insert.executeQuery();
            ResultSetMetaData rss = rs.getMetaData();
           c = rss.getColumnCount();
           DefaultTableModel df =(DefaultTableModel)jTable1.getModel();
           df.setRowCount(0);
            
           while(rs.next()){
               
               Vector v2 = new Vector();
               
               for(int i=1; i<=c ; i++){
                   
                   v2.add(rs.getString("nomGroup"));
                   v2.add(rs.getInt("nombre"));
                   v2.add(rs.getString("niveau"));
                   v2.add(rs.getInt("nbSeances"));
                   v2.add(rs.getString("seancesProch"));
                   v2.add(rs.getString("heur"));
               }
               df.addRow(v2);
           }
            
            
        } 
        catch (ClassNotFoundException ex) {
            Logger.getLogger(group.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            Logger.getLogger(group.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
    private void btnCreerGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreerGroupActionPerformed
        // TODO add your handling code here:
        String nomGroup= txtNomGroup.getText();
        String niveau = txtNiveau.getText();
        String date = txtDate.getText();
        String heur= txtHeur.getText();
        String loginP = "ens1";
        if(nomGroup.equals("") || niveau.equals("") || date.equals("") || heur.equals("")){
        JOptionPane.showMessageDialog(this,"Vérifier vos données");
    }else
        {
            boolean bb;
            //verifer la date 
            java.util.Date datee = Calendar.getInstance().getTime();  
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");  
            String dateEntrer = dateFormat.format(datee); 
            //Divition de la date pour la vérification            
            int j1,j2,m1,m2,a1,a2;
            j1=Integer.parseInt(date.substring(1, 2));
            j2=Integer.parseInt(dateEntrer.substring(1, 2));
            m1=Integer.parseInt(date.substring(4, 5));
            m2=Integer.parseInt(dateEntrer.substring(4, 5));
            a1=Integer.parseInt(date.substring(7, 10));
            a2=Integer.parseInt(dateEntrer.substring(7, 10));
            //vérification de la date 
            System.out.println(dateEntrer);
            System.out.println(date);
            if(j1>j2 || m1>m2 || a1>a2)
            {
                bb=true;
            }else{
                bb=false;
            }
            
           if(bb==true)
           {
                 Group g = new Group(nomGroup,0,niveau,0,date,heur,loginP);
                 g.Ajouter();
                 JOptionPane.showMessageDialog(this,"Group Créer");
                 table_update();
                 txtNomGroup.setText("");
                 txtNiveau.setText("");
                 txtDate.setText("");
                 txtHeur.setText(""); 
           }    else
                {
                 JOptionPane.showMessageDialog(this,"Date non valide!");
                }
        }
        
      
    }//GEN-LAST:event_btnCreerGroupActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel df =(DefaultTableModel)jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        nomG = df.getValueAt(selectedIndex, 0).toString();
            txtNomGroup.setText(df.getValueAt(selectedIndex, 0).toString());
            txtNiveau.setText(df.getValueAt(selectedIndex, 2).toString());
            txtDate.setText(df.getValueAt(selectedIndex, 4).toString());
            txtHeur.setText(df.getValueAt(selectedIndex, 5).toString());
            txtNb.setText(df.getValueAt(selectedIndex, 3).toString());
            String ch = df.getValueAt(selectedIndex, 3).toString();
             nombreSeances=Integer.parseInt(ch);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
         DefaultTableModel df =(DefaultTableModel)jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        
        if(selectedIndex == -1){
            JOptionPane.showMessageDialog(this,"Aucun Group séléctionner!");
        }else{
            int nombre = Integer.parseInt(df.getValueAt(selectedIndex, 1).toString());
        String nomm = (String) df.getValueAt(selectedIndex, 0);
        String nomGroup;
        String niveau;
        String date;
        String heur;
        
        nomGroup = txtNomGroup.getText();
        niveau = txtNiveau.getText();
        date = txtDate.getText();
        heur = txtHeur.getText();
        if(nomGroup.equals("") ||niveau.equals("") || date.equals("") || heur.equals("")){
            JOptionPane.showMessageDialog(this,"Erreur!  Tous les champs sont obligatoire");
        }else{
             String loginP = "ens1";
        Group g = new Group(nomGroup,niveau,date,heur,loginP);
        g.Modifier(nomm);
        JOptionPane.showMessageDialog(this,"Mise a jour effectué");
            table_update();
            txtNomGroup.setText("");
            txtNiveau.setText("");
            txtDate.setText("");
            txtHeur.setText("");
        }
        }
           
       
       
        
    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
       int selectedIndex = jTable1.getSelectedRow();
       if(selectedIndex == -1){
           JOptionPane.showMessageDialog(this,"Aucun group séléctionner!");
       }else{
           int dialogResult = JOptionPane.showConfirmDialog(null, "Vous voulez supprimer ce group ? ", "Warning", JOptionPane.YES_NO_OPTION);
        if(dialogResult == JOptionPane.YES_OPTION){
           
        DefaultTableModel df =(DefaultTableModel)jTable1.getModel();
        
        String nomm = (String) df.getValueAt(selectedIndex, 0);
        Group g = new Group(nomm);
        g.Supprimer();
         JOptionPane.showMessageDialog(this,"Group Supprimer");
            table_update();
            txtNomGroup.setText("");
            txtNiveau.setText("");
            txtDate.setText("");
            txtHeur.setText("");
      }  
       }
        
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int nbSeance = Integer.parseInt(txtNb.getText());
        nbSeance++;
        txtNb.setText(Integer.toString(nbSeance));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int nbSeance = Integer.parseInt(txtNb.getText());
        if(nbSeance>0){
            nbSeance--;
            txtNb.setText(Integer.toString(nbSeance));
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnGroupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroupsActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnGroupsActionPerformed

    private void btnEtrudiantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEtrudiantsActionPerformed
        // TODO add your handling code here:
        Etudiant et = new Etudiant();
        group gr = new group();
        et.setVisible(true);
        gr.setVisible(false);
        dispose();
    }//GEN-LAST:event_btnEtrudiantsActionPerformed

    private void btnConfirmerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmerActionPerformed
        // TODO add your handling code here:
        int dialogResult = JOptionPane.showConfirmDialog(null, "Vous voulez Modifier le nombre des séances ? ", "Warning", JOptionPane.YES_NO_OPTION);
        
       if(dialogResult == JOptionPane.YES_OPTION){
        DefaultTableModel df =(DefaultTableModel)jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow();
        String nb;
        nb =txtNb.getText();
        if(nb.equals("")){
            JOptionPane.showMessageDialog(this,"Erreur!  Nombre des Séances Obligatoire !");
        }else{
           int nbSeances = Integer.parseInt(nb);
        Group g = new Group(nbSeances,nomG );
        g.nbSeances(nombreSeances);
        JOptionPane.showMessageDialog(this,"Mise a jour de nombre des Séances Terminer");
        table_update(); 
        }
        
       }else{
            JOptionPane.showMessageDialog(this,"Opération Annuler");
       }
       
    }//GEN-LAST:event_btnConfirmerActionPerformed

    private void btnCoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoursActionPerformed
        // TODO add your handling code here:
         Cour c=null;
        try {
            c = new Cour();
        } catch (MalformedURLException ex) {
            Logger.getLogger(group.class.getName()).log(Level.SEVERE, null, ex);
        }
        group gr = new group();
        c.setVisible(true);
        gr.setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCoursActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(group.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(group.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(group.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(group.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new group().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmer;
    private javax.swing.JButton btnCours;
    private javax.swing.JButton btnCreerGroup;
    private javax.swing.JButton btnEtrudiants;
    private javax.swing.JButton btnGroups;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JLabel date11;
    private javax.swing.JLabel heur11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtHeur;
    private javax.swing.JTextField txtNb;
    private javax.swing.JTextField txtNiveau;
    private javax.swing.JTextField txtNomGroup;
    // End of variables declaration//GEN-END:variables
}
